# Generated by Django 2.1.1 on 2018-09-20 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewiew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=512)),
                ('reviewer_first_name', models.CharField(max_length=30)),
                ('reviewer_last_name', models.CharField(max_length=30)),
                ('review_date', models.DateTimeField(default=datetime.datetime(2018, 9, 20, 8, 56, 41, 370608))),
                ('reviewer_picture', models.ImageField(default='pic_folder/no-img.jpg', upload_to='avatars/')),
            ],
        ),
    ]
