# Generated by Django 2.1.1 on 2018-09-20 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rewiew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewiew',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
