# Generated by Django 2.1.1 on 2018-09-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180920_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage_text', models.CharField(max_length=256)),
            ],
        ),
    ]
