# Generated by Django 2.1.1 on 2018-09-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_advantager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advantager',
            new_name='Advantage',
        ),
    ]
