# Generated by Django 2.1.1 on 2018-09-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180920_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='advantage_title',
            field=models.CharField(default='Some text', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advantage',
            name='advantage_text',
            field=models.CharField(max_length=1024),
        ),
    ]
