# Generated by Django 2.1.1 on 2018-09-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='advantage_picture',
            field=models.ImageField(default='pic_folder/no-img.jpg', upload_to='advantage_pic/'),
        ),
    ]
